#!/usr/bin/expect

spawn sftp root@192.168.1.110
expect "password:"
send "root\n"
expect "sftp>"
send "cd /lib/modules/4.19.0-xilinx/kernel/drivers\n"
expect "sftp>"
send "put ./sparrow.ko\n"
expect "sftp>"
###send "sync\n"
expect "sftp>"
send "exit\n"
interact
